#pragma once
#include "Constants.h"
#define TYPE_ANIMAL 'A'
#define TYPE_PLANT 'P'

#define SPREAD_RATE 49

#define STRENGTH_PLANT 0
#define INITIATIVE_PLANT 0

#define STRENGTH_ANTELOPE 4
#define INITIATIVE_ANTELOPE 4
#define NAME_ANTELOPE "ANTELOPE"
#define DRAW_ANTELOPE 65

#define STRENGTH_BELLADONNA 99
#define NAME_BELLADONNA "BELLADONNA"
#define DRAW_BELLADONNA 225

#define STRENGTH_FOX 3
#define INITIATIVE_FOX 7
#define NAME_FOX "FOX"
#define DRAW_FOX 70

#define NAME_GRASS "GRASS"
#define DRAW_GRASS 193

#define NAME_GURANA "GUARANA"
#define DRAW_GUARANA 245

#define STRENGTH_HUMAN 5
#define INITIATIVE_HUMAN 4
#define NAME_HUMAN "HUMAN"
#define DRAW_NORMAL_HUMAN 104
#define DRAW_SUPER_HUMAN 72

#define STRENGTH_SHEEP 4 
#define INITIATIVE_SHEEP 4
#define NAME_SHEEP "SHEEP"
#define DRAW_SHEEP 83

#define STRENGTH_SOSNOWSKY 10
#define NAME_SOSNOWSKY "SOSNOWSKY"
#define DRAW_SOSNOWSKY 197

#define NAME_SOW_THISTLE "SOW THISTLE"
#define DRAW_SOW_THISTLE 207

#define STRENGTH_TURTLE 2
#define INITIATIVE_TURTLE 1
#define NAME_TURTLE "TURTLE"
#define DRAW_TURTLE 84

#define STRENGTH_WOLF 9
#define INITIATIVE_WOLF 5
#define NAME_WOLF "WOLF"
#define DRAW_WOLF 87

#define R_KEY 114
#define S_KEY 115
#define L_KEY 108
#define RIGHT_ARROW 77
#define UP_ARROW 80
#define LEFT_ARROW 75
#define DOWN_ARROW 72
#define ABILITY_SET_STRENGTH 10
#define ABILITY_COOLDOWN 10
#define ABILITY_DURATION 5

#define DRAW_WALL 219
#define DRAW_SPACE 32